# Generated by Django 5.1.2 on 2025-01-07 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AntiSala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "limpeza",
                    models.CharField(
                        choices=[("L", "Limpo"), ("M", "Mais ou Menos"), ("S", "Sujo")],
                        default="L",
                        max_length=1,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/salas/"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalaCofre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "limpeza",
                    models.CharField(
                        choices=[("L", "Limpo"), ("M", "Mais ou Menos"), ("S", "Sujo")],
                        default="L",
                        max_length=1,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/salas/"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalaEnergia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "limpeza",
                    models.CharField(
                        choices=[("L", "Limpo"), ("M", "Mais ou Menos"), ("S", "Sujo")],
                        default="L",
                        max_length=1,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/salas/"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalaTelecom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "limpeza",
                    models.CharField(
                        choices=[("L", "Limpo"), ("M", "Mais ou Menos"), ("S", "Sujo")],
                        default="L",
                        max_length=1,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/salas/"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegistroGeral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_sala",
                    models.CharField(
                        choices=[
                            ("ANTISALA", "Antisala"),
                            ("COFRE", "SalaCofre"),
                            ("TELECOM", "SalaTelecom"),
                            ("ENERGIA", "SalaEnergia"),
                        ],
                        max_length=10,
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=250, null=True)),
                ("temperatura", models.DecimalField(decimal_places=2, max_digits=5)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
