# Generated by Django 5.1.2 on 2024-10-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app", "0002_delete_antisala_delete_salacofre_delete_salaenergia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AntiSala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "limpeza",
                    models.CharField(
                        choices=[("L", "Limpo"), ("M", "Mais ou Menos"), ("S", "Sujo")],
                        default="L",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalaCofre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "limpeza",
                    models.CharField(
                        choices=[("L", "Limpo"), ("M", "Mais ou Menos"), ("S", "Sujo")],
                        default="L",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalaEnergia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "limpeza",
                    models.CharField(
                        choices=[("L", "Limpo"), ("M", "Mais ou Menos"), ("S", "Sujo")],
                        default="L",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalaTelecom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "limpeza",
                    models.CharField(
                        choices=[("L", "Limpo"), ("M", "Mais ou Menos"), ("S", "Sujo")],
                        default="L",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
