# Generated by Django 5.1.2 on 2024-10-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroGeral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_sala",
                    models.CharField(
                        choices=[
                            ("ANTISALA", "Antisala"),
                            ("COFRE", "SalaCofre"),
                            ("TELECOM", "SalaTelecom"),
                            ("ENERGIA", "SalaEnergia"),
                        ],
                        max_length=10,
                    ),
                ),
                ("observacao", models.CharField(blank=True, max_length=250, null=True)),
                ("temperatura", models.DecimalField(decimal_places=2, max_digits=5)),
                ("data_criacao", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
