# Generated by Django 5.1.2 on 2024-11-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_registrogeral_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="antisala",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/salas/"),
        ),
        migrations.AddField(
            model_name="salacofre",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/salas/"),
        ),
        migrations.AddField(
            model_name="salaenergia",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/salas/"),
        ),
        migrations.AddField(
            model_name="salatelecom",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/salas/"),
        ),
    ]
