# Generated by Django 5.1.2 on 2024-11-26 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_antisala_registro_geral_salacofre_registro_geral_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antisala",
            name="registro_geral",
        ),
        migrations.RemoveField(
            model_name="salacofre",
            name="registro_geral",
        ),
        migrations.RemoveField(
            model_name="salaenergia",
            name="registro_geral",
        ),
        migrations.RemoveField(
            model_name="salatelecom",
            name="registro_geral",
        ),
    ]
