# Generated by Django 5.1.2 on 2024-11-26 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_remove_antisala_registro_geral_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="antisala",
            name="registro_geral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.registrogeral",
            ),
        ),
        migrations.AddField(
            model_name="salacofre",
            name="registro_geral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.registrogeral",
            ),
        ),
        migrations.AddField(
            model_name="salaenergia",
            name="registro_geral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.registrogeral",
            ),
        ),
        migrations.AddField(
            model_name="salatelecom",
            name="registro_geral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.registrogeral",
            ),
        ),
    ]
